#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

export PATH=$PATH:/usr/local/sbin/
export PATH=$PATH:/usr/sbin/
export PATH=$PATH:/sbin
export DEBIAN_FRONTEND=noninteractive

install() {
# Need to get compatable versions of libtorrent-rasterbar and python-libtorrent
# I have compiled these deb packages and uploaded them for use until a better method is found
#cd /tmp
#wget -q http://jamied.pwp.blueyonder.co.uk/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#wget -q http://jamied.pwp.blueyonder.co.uk/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

#/usr/bin/dpkg -i /tmp/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#/usr/bin/dpkg -i /tmp/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

#rm /tmp/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#rm /tmp/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

apt-get -y install -t precise deluge-common deluged deluge-web deluge-console

xmlstarlet ed -L -u "//services/deluge/done" -v 1 -n ${OMV_CONFIG_FILE}
}

old() {
# Need to get compatable versions of libtorrent-rasterbar and python-libtorrent
# I have compiled these deb packages and uploaded them for use until a better method is found
cd /tmp
#wget -q http://jamied.pwp.blueyonder.co.uk/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#wget -q http://jamied.pwp.blueyonder.co.uk/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

#/usr/bin/dpkg -i /tmp/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#/usr/bin/dpkg -i /tmp/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

#rm /tmp/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_amd64.deb
#rm /tmp/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_amd64.deb

wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-common_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-console_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-web_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluged_1.3.5-0ubuntu2~precise2_all.deb

# Install latest versions so that usrs can upgrade if they want
# apt-get -y install -t precise deluge-common deluged deluge-web deluge-console

/usr/bin/dpkg -i deluge-common_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-console_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-web_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluged_1.3.5-0ubuntu2~precise2_all.deb

xmlstarlet ed -L -u "//services/deluge/done" -v 1 -n ${OMV_CONFIG_FILE}
}

case "$2" in
  install)
    install
    ;;
  old)
    old
    ;;
  *)
    exit 1
esac
