#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

export PATH=$PATH:/usr/local/sbin/
export PATH=$PATH:/usr/sbin/
export PATH=$PATH:/sbin
export DEBIAN_FRONTEND=noninteractive



install_libs() {
# Need to get compatable versions of libtorrent-rasterbar and python-libtorrent
# I have compiled these deb packages and uploaded them for use until a better method is found
URL_LINK="http://dh2k.omv-extras.org/debian/pool/main/libt/libtorrent-rasterbar/"

cd /tmp

arch=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')

if [ $arch -eq 32 ]; then
    echo "Installing libs for a 32 bit system"
    MCN="i386"
elif [ $arch -eq 64 ]; then
    echo "Installing libs for a 64 bit system"
    MCN="amd64"
else
    echo "Installing arm type libs"
    MCN="armhf"
fi

wget -q "${URL_LINK}libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb"
wget -q "${URL_LINK}python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb"

dpkg -i "libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb"

rm -f "/tmp/libtorrent-rasterbar7_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb"
rm -f "/tmp/python-libtorrent_0.16.17-1ubuntu3~ppa1~precise_${MCN}.deb"

apt-get -y install libboost-system-dev libboost-python-dev
}

install() {
install_libs;

apt-get -y install -t precise deluge-common deluged deluge-web deluge-console

xmlstarlet ed -L -u "//services/deluge/done" -v 1 -n ${OMV_CONFIG_FILE}
}

old() {
install_libs;

wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-common_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-console_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-web_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluged_1.3.5-0ubuntu2~precise2_all.deb

/usr/bin/dpkg -i deluge-common_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-console_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-web_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluged_1.3.5-0ubuntu2~precise2_all.deb

xmlstarlet ed -L -u "//services/deluge/done" -v 1 -n ${OMV_CONFIG_FILE}
}libboost-system-dev, libboost-python-dev

case "$2" in
  install)
    install
    ;;
  old)
    old
    ;;
  *)
    exit 1
esac
