#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

export PATH=$PATH:/usr/local/sbin/
export PATH=$PATH:/usr/sbin/
export PATH=$PATH:/sbin
export DEBIAN_FRONTEND=noninteractive

OMV_DELUGE_XPATH="/config/services/deluge"

if [ ! -f "/lib/systemd/system/deluge-web.service" ]; then
    cat <<EOF > /lib/systemd/system/deluge-web.service
[Unit]
Description=Deluge Bittorrent Client Web Interface
After=network-online.target

[Service]
Type=simple

User=deluge-daemon
Group=users
UMask=000

ExecStart=/usr/bin/deluge-web

Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF
    systemctl daemon-reload
fi

if [ "$(omv_config_get "${OMV_DELUGE_XPATH}/enable")" = "1" ]; then
    systemctl restart deluge-web.service
    systemctl enable deluge-web.service
else
    systemctl stop deluge-web.service
    systemctl disable deluge-web.service
fi

reset() {
if [ "$(omv_config_get "${OMV_DELUGE_XPATH}/done")" = "1" ]; then
    xmlstarlet ed -L -u "/config/services/deluge/done" -v 0 ${OMV_CONFIG_FILE}
    echo "Use this section to install another version of Deluge."
    echo ""
    echo "If you reset in error, just click start again"
    echo "and you will return to the plugin screen."
    echo ""
else
    echo "If you reset in error, just click start again"
    echo "and you will return to the install selection screen."
    echo ""
    xmlstarlet ed -L -u "/config/services/deluge/done" -v 1 ${OMV_CONFIG_FILE}
fi

echo "Done"
exit
}

install() {
apt-get -y -q install deluge deluge-common deluged deluge-web deluge-console

xmlstarlet ed -L -u "/config/services/deluge/done" -v 1 ${OMV_CONFIG_FILE}
}

old() {
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-common_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-console_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-web_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge_1.3.5-0ubuntu2~precise2_all.deb
wget -q http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluged_1.3.5-0ubuntu2~precise2_all.deb

/usr/bin/dpkg -i deluge-common_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-console_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-web_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge-gtk_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluge_1.3.5-0ubuntu2~precise2_all.deb
/usr/bin/dpkg -i deluged_1.3.5-0ubuntu2~precise2_all.deb

xmlstarlet ed -L -u "/config/services/deluge/done" -v 1 ${OMV_CONFIG_FILE}
}

case "$2" in
  install)
    install
    ;;
  old)
    old
    ;;
  reset)
    reset
    ;;
  *)
    exit
esac
