#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        if [ -f "/var/run/deluged.pid" ]; then
            PID=$(cat /var/run/deluged.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        if [ -f "/var/run/deluge.pid" ]; then
            PID=$(cat /var/run/deluge.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        omv_config_delete "//services/deluge"

        userdel -r deluge-daemon

        ( sleep 60; apt-get --yes --auto-remove --purge remove python-libtorrent libtorrent-rasterbar7 deluge-common deluge-gtk deluge deluged deluge-web deluge-console 2>&1) &

    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0